### ISSUE TITLE
Remove old "ide-configs"

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#190]
We now have `.editorconfig`

**Comment by gastaldi** [comment]
.editorconfig does not support all the settings specific for Intellij, like preferred member order while reformatting (constructor/fields/methods) and other small tweaks, but it provides the basic criteria of acceptance. 

-1 to removing it as such preferences are preferred when using IntelliJ

**Comment by ALRubinger** [comment]
@gastaldi Are the ide-settings compatible with the `.editorconfig` ones?  Do they, used together, arrive at the correct result?

We need checkstyle validating the build, else this is all for naught. :)

**Comment by gastaldi** [comment]
Yes, Intellij generated the .editorconfig from the ide settings from this
XML, they are best if used together.

Em 20 de mar de 2017 22:23, "Andrew Lee Rubinger" <notifications@github.com>
escreveu:

@gastaldi <https://github.com/gastaldi> Are the ide-settings compatible
with the .editorconfig ones? Do they, used together, arrive at the correct
result?

We need checkstyle validating the build, else this is all for naught. :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/redhat-kontinuity/catapult/issues/190#issuecomment-287948507>,
or mute the thread

**Comment by ALRubinger** [comment]
Closing per @gastaldi comments
